# Generated by Django 5.0.4 on 2024-11-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immunization_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="immunizationschedule",
            name="child_weight",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
