# Generated by Django 5.0.4 on 2024-11-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immunization_api", "0002_alter_immunizationschedule_child_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiver",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="caregiver",
            name="occupation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="child",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
        migrations.AddField(
            model_name="person",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
