# Generated by Django 5.0.4 on 2024-11-29 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("immunization_api", "0002_alter_immunizationschedule_child_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="immunization_api.person",
                    ),
                ),
                ("specialization", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
            bases=("immunization_api.person",),
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("established_date", models.DateField()),
                ("about", models.TextField()),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Total number of beds available"
                    ),
                ),
            ],
        ),
    ]
