# Generated by Django 5.0.4 on 2024-11-29 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="hospital",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="hospital.hospital",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hospital",
            name="address",
            field=models.CharField(),
        ),
    ]
